using System.IO;
using System.Runtime.InteropServices;
using LibVLCSharp.Shared;
using NexusExplorer.Services;
using System.Windows.Threading;

namespace NexusExplorer.Tests;

// Native output test assets are generated by the test itself: a real PCM WAV and raw-video AVI.
public class VideoPlaybackSmokeTests : IDisposable
{
    private readonly TestHost _host = new();
    public void Dispose() => _host.Dispose();
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    private static extern IntPtr CreateWindowEx(int exStyle, string className, string title, int style, int x, int y, int width, int height, IntPtr parent, IntPtr menu, IntPtr instance, IntPtr param);
    [DllImport("user32.dll")] private static extern bool DestroyWindow(IntPtr window);

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Mp4NativeView_SeekBothDirectionsRetainsVideoAndAudio(bool hardware)
    {
        var asset = Path.Combine(AppContext.BaseDirectory, "Assets", "seek-h264-aac.mp4");
        Assert.True(File.Exists(asset), "H.264/AAC 测试素材缺失，不能计为通过。");
        var path = Path.Combine(_host.RootDir, "seek.mp4"); File.Copy(asset, path);
        await WpfTestHost.RunAsync(async () =>
        {
            using var engine = new MediaPlayerService(Dispatcher.CurrentDispatcher) { HardwareDecoding = hardware };
            await engine.InitializeAsync();
            using var view = new LibVLCSharp.WPF.VideoView();
            var window = new System.Windows.Window { Content = view, Width = 340, Height = 220,
                Left = -5000, Top = -5000, ShowInTaskbar = false, ShowActivated = false };
            window.Show(); view.MediaPlayer = engine.NativePlayer;
            try
            {
                await engine.PlayAsync(path, false);
                await WaitUntilAsync(() => engine.Snapshot.IsPlaying && engine.Snapshot.Duration.TotalSeconds > 3);
                await WaitUntilAsync(() =>
                {
                    using var active = engine.NativePlayer!.Media;
                    return active is not null && active.Statistics.DecodedVideo > 0 && active.Statistics.DecodedAudio > 0;
                });
                foreach (var fraction in new[] { .65f, .15f, .5f })
                {
                    await engine.SeekAsync(fraction);
                    await WaitUntilAsync(() => Math.Abs(engine.Snapshot.Position.TotalSeconds - 4 * fraction) < .8);
                    Assert.True(engine.NativePlayer!.AudioTrack >= 0);
                    var image = Path.Combine(_host.RootDir, $"seek-{fraction}.png");
                    Assert.True(engine.NativePlayer.TakeSnapshot(0, image, 320, 180));
                    await WaitUntilAsync(() => File.Exists(image) && new FileInfo(image).Length > 0);
                    using var media = engine.NativePlayer.Media;
                    Assert.True(media!.Statistics.DecodedVideo > 0);
                    Assert.True(media.Statistics.DecodedAudio > 0);
                }
                await engine.StopAndReleaseAsync();
                using var exclusive = File.Open(path, FileMode.Open, FileAccess.ReadWrite, FileShare.None);
            }
            finally { await engine.StopAndReleaseAsync(); view.MediaPlayer = null; window.Close(); }
        });
    }

    [Theory]
    [InlineData(64, 48, false)]
    [InlineData(320, 240, true)]
    [InlineData(640, 360, true)]
    public async Task NativeVideo_SwitchSeekAndRelease_RealSyntheticMediaAsync(int expectedWidth, int expectedHeight, bool audio)
    {
        var video = SyntheticMedia.WriteAvi(Path.Combine(_host.RootDir, "video.avi"), expectedWidth, expectedHeight, audio);
        using var engine = new MediaPlayerService(Dispatcher.CurrentDispatcher) { HardwareDecoding = false };
        await engine.InitializeAsync();
        var window = CreateWindowEx(0, "STATIC", "Nexus test video", unchecked((int)0x80000000), -5000, -5000, 96, 64, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
        Assert.NotEqual(IntPtr.Zero, window);
        try
        {
            engine.NativePlayer!.Hwnd = window;
            await engine.PlayAsync(video, false);
            await WaitUntilAsync(() => engine.NativePlayer!.State is VLCState.Playing && engine.NativePlayer!.Time > 0);
            uint width = 0, height = 0;
            Assert.True(engine.NativePlayer!.Size(0, ref width, ref height));
            Assert.Equal((uint)expectedWidth, width); Assert.Equal((uint)expectedHeight, height);
            if (audio) Assert.True(engine.NativePlayer.AudioTrack >= 0, "带音轨视频必须实际加载音轨。");
            var snapshot = Path.Combine(_host.RootDir, "frame.png");
            Assert.True(engine.NativePlayer.TakeSnapshot(0, snapshot, 64, 48));
            await WaitUntilAsync(() => File.Exists(snapshot) && new FileInfo(snapshot).Length > 0);
            for (var i = 0; i < 3; i++)
            {
                await engine.SeekAsync(0.5f);
                await WaitUntilAsync(() => engine.NativePlayer.Time >= 1200);
                await engine.PlayAsync(video, false);
                await WaitUntilAsync(() => engine.NativePlayer.State == VLCState.Playing);
            }
            await engine.StopAndReleaseAsync();
            Assert.Null(engine.CurrentPath);
            using var exclusive = new FileStream(video, FileMode.Open, FileAccess.ReadWrite, FileShare.None);
        }
        finally { DestroyWindow(window); }
    }
    [Fact]
    public async Task NativeAudio_PcmSwitchAndReleaseAsync()
    {
        var wav = SyntheticMedia.WriteWave(Path.Combine(_host.RootDir, "test.wav"));
        using var engine = new MediaPlayerService(Dispatcher.CurrentDispatcher);
        await engine.PlayAsync(wav, true);
        await WaitUntilAsync(() => engine.Snapshot.IsPlaying && engine.Snapshot.Duration > TimeSpan.Zero);
        await engine.SeekAsync(0.5f);
        await engine.TogglePauseAsync();
        await WaitUntilAsync(() => engine.Snapshot.IsPaused);
        await engine.TogglePauseAsync();
        await engine.StopAndReleaseAsync();
        using var exclusive = new FileStream(wav, FileMode.Open, FileAccess.ReadWrite, FileShare.None);
    }
    private static async Task WaitUntilAsync(Func<bool> condition)
    {
        var deadline = DateTime.UtcNow.AddSeconds(12);
        while (DateTime.UtcNow < deadline)
        { if (condition()) return; await Task.Delay(50); }
        Assert.True(condition(), "真实媒体播放未达到预期状态。");
    }
}
internal static class SyntheticMedia
{
    private static void FourCc(BinaryWriter writer, string text) => writer.Write(System.Text.Encoding.ASCII.GetBytes(text));
    public static string WriteWave(string path)
    {
        const int rate = 44100, channels = 2, seconds = 4;
        using var writer = new BinaryWriter(File.Create(path));
        var bytes = rate * channels * seconds * 2;
        FourCc(writer, "RIFF"); writer.Write(36 + bytes); FourCc(writer, "WAVE"); FourCc(writer, "fmt "); writer.Write(16);
        writer.Write((short)1); writer.Write((short)channels); writer.Write(rate); writer.Write(rate * channels * 2); writer.Write((short)(channels * 2)); writer.Write((short)16);
        FourCc(writer, "data"); writer.Write(bytes);
        for (var i = 0; i < rate * seconds; i++) for (var c = 0; c < channels; c++) writer.Write((short)(Math.Sin(2 * Math.PI * (c == 0 ? 440 : 660) * i / rate) * 8000));
        return path;
    }
    public static string WriteAvi(string path, int width = 64, int height = 48, bool audio = false)
    {
        const int rate = 10, frames = 40, audioRate = 44100, audioFrameBytes = audioRate / rate * 4;
        var size = width * height * 3;
        using var w = new BinaryWriter(File.Create(path));
        FourCc(w, "RIFF"); w.Write(0); FourCc(w, "AVI ");
        long Begin(string type) { FourCc(w, "LIST"); var p = w.BaseStream.Position; w.Write(0); FourCc(w, type); return p; }
        void End(long p) { var end = w.BaseStream.Position; w.BaseStream.Position = p; w.Write((int)(end - p - 4)); w.BaseStream.Position = end; }
        var hdrl = Begin("hdrl");
        FourCc(w, "avih"); w.Write(56); w.Write(1000000 / rate); w.Write(size * rate); w.Write(0); w.Write(0);
        w.Write(frames); w.Write(0); w.Write(audio ? 2 : 1); w.Write(size); w.Write(width); w.Write(height); for (var i = 0; i < 4; i++) w.Write(0);
        var strl = Begin("strl");
        FourCc(w, "strh"); w.Write(56); FourCc(w, "vids"); FourCc(w, "DIB "); w.Write(0); w.Write((short)0); w.Write((short)0);
        w.Write(0); w.Write(1); w.Write(rate); w.Write(0); w.Write(frames); w.Write(size); w.Write(-1); w.Write(0); w.Write((short)0); w.Write((short)0); w.Write((short)width); w.Write((short)height);
        FourCc(w, "strf"); w.Write(40); w.Write(40); w.Write(width); w.Write(height); w.Write((short)1); w.Write((short)24); w.Write(0); w.Write(size); w.Write(0); w.Write(0); w.Write(0); w.Write(0);
        End(strl);
        if (audio)
        {
            var audioList = Begin("strl");
            FourCc(w, "strh"); w.Write(56); FourCc(w, "auds"); w.Write(0); w.Write(0); w.Write((short)0); w.Write((short)0);
            w.Write(0); w.Write(4); w.Write(audioRate * 4); w.Write(0); w.Write(audioRate * frames / rate); w.Write(audioFrameBytes); w.Write(-1); w.Write(4);
            for (var i = 0; i < 4; i++) w.Write((short)0);
            FourCc(w, "strf"); w.Write(16); w.Write((short)1); w.Write((short)2); w.Write(audioRate); w.Write(audioRate * 4); w.Write((short)4); w.Write((short)16);
            End(audioList);
        }
        End(hdrl); var movi = Begin("movi");
        for (var frame = 0; frame < frames; frame++)
        {
            FourCc(w, "00db"); w.Write(size);
            for (var y = 0; y < height; y++) for (var x = 0; x < width; x++)
            { w.Write((byte)(x * 3)); w.Write((byte)(y * 4)); w.Write((byte)(64 + frame * 3)); }
            if (audio)
            {
                FourCc(w, "01wb"); w.Write(audioFrameBytes);
                for (var sample = 0; sample < audioRate / rate; sample++)
                    for (var channel = 0; channel < 2; channel++)
                        w.Write((short)(Math.Sin(2 * Math.PI * (channel == 0 ? 440 : 660) * (frame * audioRate / rate + sample) / audioRate) * 8000));
            }
        }
        End(movi); var length = w.BaseStream.Length; w.BaseStream.Position = 4; w.Write((int)length - 8); return path;
    }
}
